# #API References
#
# The **Phyllo API** is built on RESTful principles and returns JSON encoded responses and accepts JSON payloads. It is only available through HTTPS to ensure the security of the data in transfer. These APIs must be called only from your server and never from your app / frontend as this is a security concern.  The API operates in three environments: **sandbox**, **staging** and **production**.  The sandbox environment returns mock data and is used for testing the basic functionality of the system.  The staging environment is exactly like a production environment but with certain limitations. It is used for your internal testing and development purposes.  The production environment connects to real platform accounts and all data reads and writes are made to live accounts. This is what you would use to get data for your customers.
#
# The version of the OpenAPI document: v1.0
# Contact: support@getphyllo.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.6.0
#

require "date"
require "time"

module Phyllo
  class Content1Engagement
    # Total likes.
    attr_accessor :like_count

    # Total dislikes.
    attr_accessor :dislike_count

    # Total comments.
    attr_accessor :comment_count

    # Total organic impressions.
    attr_accessor :impression_organic_count

    # Total organic reach.
    attr_accessor :reach_organic_count

    # Total item saves.
    attr_accessor :save_count

    # Total views.
    attr_accessor :view_count

    # If format is `video` - total watch time in hours.
    attr_accessor :watch_time_in_hours

    # Total shares.
    attr_accessor :share_count

    # Total paid impressions.
    attr_accessor :impression_paid_count

    # Total paid reach.
    attr_accessor :reach_paid_count

    # Percentage of emails that have been opened
    attr_accessor :email_open_rate

    # Percentage of emails that have been clicked
    attr_accessor :email_click_rate

    # Number of unsubscribes on the email
    attr_accessor :unsubscribe_count

    # Number of email subscribers that report this post as spam
    attr_accessor :spam_report_count

    # Total web click count on the content item
    attr_accessor :click_count

    attr_accessor :additional_info

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        like_count: :like_count,
        dislike_count: :dislike_count,
        comment_count: :comment_count,
        impression_organic_count: :impression_organic_count,
        reach_organic_count: :reach_organic_count,
        save_count: :save_count,
        view_count: :view_count,
        watch_time_in_hours: :watch_time_in_hours,
        share_count: :share_count,
        impression_paid_count: :impression_paid_count,
        reach_paid_count: :reach_paid_count,
        email_open_rate: :email_open_rate,
        email_click_rate: :email_click_rate,
        unsubscribe_count: :unsubscribe_count,
        spam_report_count: :spam_report_count,
        click_count: :click_count,
        additional_info: :additional_info
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        like_count: :Integer,
        dislike_count: :Integer,
        comment_count: :Integer,
        impression_organic_count: :Integer,
        reach_organic_count: :Integer,
        save_count: :Integer,
        view_count: :Integer,
        watch_time_in_hours: :Float,
        share_count: :Integer,
        impression_paid_count: :Integer,
        reach_paid_count: :Integer,
        email_open_rate: :Float,
        email_click_rate: :Float,
        unsubscribe_count: :Integer,
        spam_report_count: :Integer,
        click_count: :Integer,
        additional_info: :Content1EngagementAdditionalInfo
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :share_count,
        :impression_paid_count,
        :reach_paid_count,
        :additional_info
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if !attributes.is_a?(Hash)
        fail ArgumentError, "The input argument (attributes) must be a hash in `Phyllo::Content1Engagement` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if !self.class.attribute_map.key?(k.to_sym)
          fail ArgumentError, "`#{k}` is not a valid attribute in `Phyllo::Content1Engagement`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:like_count)
        self.like_count = attributes[:like_count]
      end

      if attributes.key?(:dislike_count)
        self.dislike_count = attributes[:dislike_count]
      end

      if attributes.key?(:comment_count)
        self.comment_count = attributes[:comment_count]
      end

      if attributes.key?(:impression_organic_count)
        self.impression_organic_count = attributes[:impression_organic_count]
      end

      if attributes.key?(:reach_organic_count)
        self.reach_organic_count = attributes[:reach_organic_count]
      end

      if attributes.key?(:save_count)
        self.save_count = attributes[:save_count]
      end

      if attributes.key?(:view_count)
        self.view_count = attributes[:view_count]
      end

      if attributes.key?(:watch_time_in_hours)
        self.watch_time_in_hours = attributes[:watch_time_in_hours]
      end

      if attributes.key?(:share_count)
        self.share_count = attributes[:share_count]
      end

      if attributes.key?(:impression_paid_count)
        self.impression_paid_count = attributes[:impression_paid_count]
      end

      if attributes.key?(:reach_paid_count)
        self.reach_paid_count = attributes[:reach_paid_count]
      end

      if attributes.key?(:email_open_rate)
        self.email_open_rate = attributes[:email_open_rate]
      end

      if attributes.key?(:email_click_rate)
        self.email_click_rate = attributes[:email_click_rate]
      end

      if attributes.key?(:unsubscribe_count)
        self.unsubscribe_count = attributes[:unsubscribe_count]
      end

      if attributes.key?(:spam_report_count)
        self.spam_report_count = attributes[:spam_report_count]
      end

      if attributes.key?(:click_count)
        self.click_count = attributes[:click_count]
      end

      if attributes.key?(:additional_info)
        self.additional_info = attributes[:additional_info]
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn "[DEPRECATED] the `list_invalid_properties` method is obsolete"
      []
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn "[DEPRECATED] the `valid?` method is obsolete"
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)
      self.class == other.class &&
        like_count == other.like_count &&
        dislike_count == other.dislike_count &&
        comment_count == other.comment_count &&
        impression_organic_count == other.impression_organic_count &&
        reach_organic_count == other.reach_organic_count &&
        save_count == other.save_count &&
        view_count == other.view_count &&
        watch_time_in_hours == other.watch_time_in_hours &&
        share_count == other.share_count &&
        impression_paid_count == other.impression_paid_count &&
        reach_paid_count == other.reach_paid_count &&
        email_open_rate == other.email_open_rate &&
        email_click_rate == other.email_click_rate &&
        unsubscribe_count == other.unsubscribe_count &&
        spam_report_count == other.spam_report_count &&
        click_count == other.click_count &&
        additional_info == other.additional_info
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [like_count, dislike_count, comment_count, impression_organic_count, reach_organic_count, save_count, view_count, watch_time_in_hours, share_count, impression_paid_count, reach_paid_count, email_open_rate, email_click_rate, unsubscribe_count, spam_report_count, click_count, additional_info].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash[key.to_s] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash[key.to_s] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash[key.to_s] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Phyllo.const_get(type)
        (klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of)) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
