# #API References
#
# The **Phyllo API** is built on RESTful principles and returns JSON encoded responses and accepts JSON payloads. It is only available through HTTPS to ensure the security of the data in transfer. These APIs must be called only from your server and never from your app / frontend as this is a security concern.  The API operates in three environments: **sandbox**, **staging** and **production**.  The sandbox environment returns mock data and is used for testing the basic functionality of the system.  The staging environment is exactly like a production environment but with certain limitations. It is used for your internal testing and development purposes.  The production environment connects to real platform accounts and all data reads and writes are made to live accounts. This is what you would use to get data for your customers.
#
# The version of the OpenAPI document: v1.0
# Contact: support@getphyllo.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.6.0
#

require "date"
require "time"

module Phyllo
  # Represents the user profile object. The profile object contains information related to the identity of the user. The data in a profile is tied to a particular work platform account that the user has connected to via Phyllo.
  class Profile
    # Unique ID of the profile.
    attr_accessor :id

    # Profile creation time (UTC date and time in ISO 8601 format)
    attr_accessor :created_at

    # Profile updation time (UTC date and time in ISO 8601 format)
    attr_accessor :updated_at

    attr_accessor :user

    attr_accessor :account

    attr_accessor :work_platform

    # Username of the connected account. This is used to uniquely identify a user on any platform and usually the name that is present in the URLs, used to tag a user etc.  Ex - For YouTube, it's the channel name in the URL and for Instagram / Twitter / TikTok etc, it's the handle.
    attr_accessor :platform_username

    # Full name of the user profile.
    attr_accessor :full_name

    # First name of the user profile.
    attr_accessor :first_name

    # Last name of the user profile.
    attr_accessor :last_name

    # Nickname of the user profile.
    attr_accessor :nick_name

    # Profile URL on the connected platform.
    attr_accessor :url

    # Description of the profile.   Ex - For Instagram it's the bio and for YouTube it's the channel introduction.
    attr_accessor :introduction

    # URL of the profile image on the platform.
    attr_accessor :image_url

    # Date of birth of the user on the platform.
    attr_accessor :date_of_birth

    # Unique identifier for the profile on the platform.
    attr_accessor :external_id

    # Account type of the user on the platform.
    attr_accessor :platform_account_type

    # Category of the user's platform account.  Ex - For Instagram it's the page type which could be beauty, fitness etc
    attr_accessor :category

    # User website listed on the platform.
    attr_accessor :website

    attr_accessor :reputation

    # Emails object.
    attr_accessor :emails

    # Phone numbers object.
    attr_accessor :phone_numbers

    # Addresses object.
    attr_accessor :addresses

    # Gender of the user.
    attr_accessor :gender

    # Country of the user on the connected platform.
    attr_accessor :country

    # User's profile name on the work platform. This is not unique, is displayed prominently on the profile, usually editable and is most commonly associated with that user's identity on the platform.  Ex - For YouTube, it's the channel name displayed on the channel page and for Instagram / Twitter / TikTok etc, it's the name displayed on the user's profile page.
    attr_accessor :platform_profile_name

    # Unique profile ID of the user on the work platform.   Ex - For YouTube it's the channel ID and for Instagram it's the Instagram page ID.
    attr_accessor :platform_profile_id

    # Timestamp when the profile was created on the platform.
    attr_accessor :platform_profile_published_at

    # **true** if the user''s profile is verified by the platform.
    attr_accessor :is_verified

    # **true** if the user''s profile is business account on the platform.
    attr_accessor :is_business

    attr_accessor :work_experiences

    attr_accessor :education

    attr_accessor :publications

    attr_accessor :certifications

    attr_accessor :volunteer_experiences

    attr_accessor :honors

    attr_accessor :projects

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        id: :id,
        created_at: :created_at,
        updated_at: :updated_at,
        user: :user,
        account: :account,
        work_platform: :work_platform,
        platform_username: :platform_username,
        full_name: :full_name,
        first_name: :first_name,
        last_name: :last_name,
        nick_name: :nick_name,
        url: :url,
        introduction: :introduction,
        image_url: :image_url,
        date_of_birth: :date_of_birth,
        external_id: :external_id,
        platform_account_type: :platform_account_type,
        category: :category,
        website: :website,
        reputation: :reputation,
        emails: :emails,
        phone_numbers: :phone_numbers,
        addresses: :addresses,
        gender: :gender,
        country: :country,
        platform_profile_name: :platform_profile_name,
        platform_profile_id: :platform_profile_id,
        platform_profile_published_at: :platform_profile_published_at,
        is_verified: :is_verified,
        is_business: :is_business,
        work_experiences: :work_experiences,
        education: :education,
        publications: :publications,
        certifications: :certifications,
        volunteer_experiences: :volunteer_experiences,
        honors: :honors,
        projects: :projects
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        id: :String,
        created_at: :Time,
        updated_at: :Time,
        user: :UserAttribute1,
        account: :AccountAttribute1,
        work_platform: :WorkPlatformAttribute1,
        platform_username: :String,
        full_name: :String,
        first_name: :String,
        last_name: :String,
        nick_name: :String,
        url: :String,
        introduction: :String,
        image_url: :String,
        date_of_birth: :String,
        external_id: :String,
        platform_account_type: :String,
        category: :String,
        website: :String,
        reputation: :Profile1Reputation,
        emails: :"Array<Profile1EmailsInner>",
        phone_numbers: :"Array<Profile1PhoneNumbersInner>",
        addresses: :"Array<Profile1AddressesInner>",
        gender: :String,
        country: :String,
        platform_profile_name: :String,
        platform_profile_id: :String,
        platform_profile_published_at: :Time,
        is_verified: :Boolean,
        is_business: :Boolean,
        work_experiences: :"Array<WorkExperience1>",
        education: :"Array<Education1>",
        publications: :"Array<Publications1>",
        certifications: :"Array<Certifications1>",
        volunteer_experiences: :"Array<VolunteerExperiences1>",
        honors: :"Array<Honors1>",
        projects: :"Array<Projects1>"
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :platform_username,
        :full_name,
        :first_name,
        :last_name,
        :nick_name,
        :introduction,
        :platform_account_type,
        :category,
        :website,
        :gender,
        :platform_profile_name,
        :platform_profile_id,
        :platform_profile_published_at
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if !attributes.is_a?(Hash)
        fail ArgumentError, "The input argument (attributes) must be a hash in `Phyllo::Profile` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if !self.class.attribute_map.key?(k.to_sym)
          fail ArgumentError, "`#{k}` is not a valid attribute in `Phyllo::Profile`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      self.id = if attributes.key?(:id)
        attributes[:id]
      end

      self.created_at = if attributes.key?(:created_at)
        attributes[:created_at]
      end

      self.updated_at = if attributes.key?(:updated_at)
        attributes[:updated_at]
      end

      self.user = if attributes.key?(:user)
        attributes[:user]
      end

      self.account = if attributes.key?(:account)
        attributes[:account]
      end

      self.work_platform = if attributes.key?(:work_platform)
        attributes[:work_platform]
      end

      self.platform_username = if attributes.key?(:platform_username)
        attributes[:platform_username]
      end

      if attributes.key?(:full_name)
        self.full_name = attributes[:full_name]
      end

      if attributes.key?(:first_name)
        self.first_name = attributes[:first_name]
      end

      if attributes.key?(:last_name)
        self.last_name = attributes[:last_name]
      end

      if attributes.key?(:nick_name)
        self.nick_name = attributes[:nick_name]
      end

      if attributes.key?(:url)
        self.url = attributes[:url]
      end

      if attributes.key?(:introduction)
        self.introduction = attributes[:introduction]
      end

      if attributes.key?(:image_url)
        self.image_url = attributes[:image_url]
      end

      if attributes.key?(:date_of_birth)
        self.date_of_birth = attributes[:date_of_birth]
      end

      if attributes.key?(:external_id)
        self.external_id = attributes[:external_id]
      end

      if attributes.key?(:platform_account_type)
        self.platform_account_type = attributes[:platform_account_type]
      end

      if attributes.key?(:category)
        self.category = attributes[:category]
      end

      if attributes.key?(:website)
        self.website = attributes[:website]
      end

      if attributes.key?(:reputation)
        self.reputation = attributes[:reputation]
      end

      if attributes.key?(:emails)
        if (value = attributes[:emails]).is_a?(Array)
          self.emails = value
        end
      end

      if attributes.key?(:phone_numbers)
        if (value = attributes[:phone_numbers]).is_a?(Array)
          self.phone_numbers = value
        end
      end

      if attributes.key?(:addresses)
        if (value = attributes[:addresses]).is_a?(Array)
          self.addresses = value
        end
      end

      self.gender = if attributes.key?(:gender)
        attributes[:gender]
      end

      if attributes.key?(:country)
        self.country = attributes[:country]
      end

      if attributes.key?(:platform_profile_name)
        self.platform_profile_name = attributes[:platform_profile_name]
      end

      if attributes.key?(:platform_profile_id)
        self.platform_profile_id = attributes[:platform_profile_id]
      end

      if attributes.key?(:platform_profile_published_at)
        self.platform_profile_published_at = attributes[:platform_profile_published_at]
      end

      if attributes.key?(:is_verified)
        self.is_verified = attributes[:is_verified]
      end

      if attributes.key?(:is_business)
        self.is_business = attributes[:is_business]
      end

      if attributes.key?(:work_experiences)
        if (value = attributes[:work_experiences]).is_a?(Array)
          self.work_experiences = value
        end
      end

      if attributes.key?(:education)
        if (value = attributes[:education]).is_a?(Array)
          self.education = value
        end
      end

      if attributes.key?(:publications)
        if (value = attributes[:publications]).is_a?(Array)
          self.publications = value
        end
      end

      if attributes.key?(:certifications)
        if (value = attributes[:certifications]).is_a?(Array)
          self.certifications = value
        end
      end

      if attributes.key?(:volunteer_experiences)
        if (value = attributes[:volunteer_experiences]).is_a?(Array)
          self.volunteer_experiences = value
        end
      end

      if attributes.key?(:honors)
        if (value = attributes[:honors]).is_a?(Array)
          self.honors = value
        end
      end

      if attributes.key?(:projects)
        if (value = attributes[:projects]).is_a?(Array)
          self.projects = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn "[DEPRECATED] the `list_invalid_properties` method is obsolete"
      invalid_properties = []
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @user.nil?
        invalid_properties.push('invalid value for "user", user cannot be nil.')
      end

      if @account.nil?
        invalid_properties.push('invalid value for "account", account cannot be nil.')
      end

      if @work_platform.nil?
        invalid_properties.push('invalid value for "work_platform", work_platform cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn "[DEPRECATED] the `valid?` method is obsolete"
      return false if @id.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      return false if @user.nil?
      return false if @account.nil?
      return false if @work_platform.nil?
      gender_validator = EnumAttributeValidator.new("String", ["MALE", "FEMALE", "OTHER", "UNSPECIFIED"])
      return false unless gender_validator.valid?(@gender)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] gender Object to be assigned
    def gender=(gender)
      validator = EnumAttributeValidator.new("String", ["MALE", "FEMALE", "OTHER", "UNSPECIFIED"])
      unless validator.valid?(gender)
        fail ArgumentError, "invalid value for \"gender\", must be one of #{validator.allowable_values}."
      end
      @gender = gender
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)
      self.class == other.class &&
        id == other.id &&
        created_at == other.created_at &&
        updated_at == other.updated_at &&
        user == other.user &&
        account == other.account &&
        work_platform == other.work_platform &&
        platform_username == other.platform_username &&
        full_name == other.full_name &&
        first_name == other.first_name &&
        last_name == other.last_name &&
        nick_name == other.nick_name &&
        url == other.url &&
        introduction == other.introduction &&
        image_url == other.image_url &&
        date_of_birth == other.date_of_birth &&
        external_id == other.external_id &&
        platform_account_type == other.platform_account_type &&
        category == other.category &&
        website == other.website &&
        reputation == other.reputation &&
        emails == other.emails &&
        phone_numbers == other.phone_numbers &&
        addresses == other.addresses &&
        gender == other.gender &&
        country == other.country &&
        platform_profile_name == other.platform_profile_name &&
        platform_profile_id == other.platform_profile_id &&
        platform_profile_published_at == other.platform_profile_published_at &&
        is_verified == other.is_verified &&
        is_business == other.is_business &&
        work_experiences == other.work_experiences &&
        education == other.education &&
        publications == other.publications &&
        certifications == other.certifications &&
        volunteer_experiences == other.volunteer_experiences &&
        honors == other.honors &&
        projects == other.projects
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, created_at, updated_at, user, account, work_platform, platform_username, full_name, first_name, last_name, nick_name, url, introduction, image_url, date_of_birth, external_id, platform_account_type, category, website, reputation, emails, phone_numbers, addresses, gender, country, platform_profile_name, platform_profile_id, platform_profile_published_at, is_verified, is_business, work_experiences, education, publications, certifications, volunteer_experiences, honors, projects].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash[key.to_s] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash[key.to_s] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash[key.to_s] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Phyllo.const_get(type)
        (klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of)) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
