language: ruby
cache: bundler
rvm:
  - 3.0
  - 3.1
  - 3.2
  - 3.3
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build phyllo.gemspec
  - gem install ./phyllo-1.0.0.gem
