# API References
#
# The **Phyllo API** is built on RESTful principles and returns JSON encoded responses and accepts JSON payloads.
# It is only available through HTTPS to ensure the security of the data in transfer. These APIs must be called only
# from your server and never from your app/frontend as this is a security concern.
#
# The API operates in three environments: **sandbox**, **staging** and **production**.
#
# The sandbox environment returns mock data and is used for testing the basic functionality of the system.
#
# The staging environment is exactly like a production environment but with certain limitations. It is used for your
# internal testing and development purposes.
#
# The production environment connects to real platform accounts and all data reads and writes are made to live accounts.
# This is what you would use to get data for your customers.
#
# The version of the OpenAPI document: v1.0
# Contact: support@getphyllo.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.6.0
#

$:.push File.expand_path("../lib", __FILE__)
require "phyllo/version"

Gem::Specification.new do |s|
  s.name = "sponsorless-phyllo"
  s.version = Phyllo::VERSION
  s.platform = Gem::Platform::RUBY
  s.authors = ["Colton Malone", "Eric Berry (coderberry)"]
  s.email = ["colton@sponsorless.com", "eric@berry.com"]
  s.homepage = "https://github.com/sponsorless/sponsorless-phyllo"
  s.summary = "Phyllo Ruby Gem"
  s.description = "Ruby client for the Phyllo API"
  s.license = "MIT"
  s.required_ruby_version = ">= 3"

  s.add_runtime_dependency "typhoeus", "~> 1.0", ">= 1.0.1"

  s.add_development_dependency "rspec", "~> 3.6", ">= 3.6.0"

  s.files = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.executables = []
  s.require_paths = ["lib"]
end
